[package]
name = "subcs"
version = "0.1.0"
authors = ["Tobias Moldan <tobias.moldan@gmail.com>"]
edition = "2018"
description = "Simple UDP Broadcast Chat Server"

[dependencies]
async-std = { version = "1.6", features = ["attributes"] }
anyhow = "1"
